- hosts: brokers
  become: yes
  tasks:

  - name: Set Broker ID
    set_fact:
      broker_id: "{{ groups['brokers'].index(inventory_hostname) + 1 }}"

  - name: Set zookeeper connection
    set_fact:
      zookeeper_connection: "{{ groups['brokers'] | map ('extract', hostvars, ['ansible_default_ipv4', 'address']) | product([':2181']) | map('join') | join(',') }}"

  - name: install openjdk
    apt:
      pkg:
      - libxt-dev
      - openjdk-11-jdk-headless
      - openjdk-11-jdk
      update_cache: yes

  - name: install wget
    apt:
      name: wget
      state: present

  - name: install gnupg2
    apt:
      name: gnupg2
      state: present


  - name: install software-properties-common
    apt:
      name: software-properties-common
      state: present


  - name: install net-tools
    apt:
      name: net-tools
      state: present


  - name: install iputils-ping
    apt:
      name: iputils-ping
      state: present

  - name: add confluent apt-key
    apt_key:
      url: https://packages.confluent.io/deb/6.1/archive.key
      state: present

  - name: add confluent's APT repository
    apt_repository:
      repo: deb https://packages.confluent.io/deb/6.1 stable main
      state: present
      filename: 'confluent'

  - name: install confluent community
    apt:
      name: confluent-community-2.13
      state: present
      update_cache: yes

  - name: Copy Kafka Server JAAS config 
    ansible.builtin.copy:
      src: kafka_server.jaas
      dest: /etc/kafka/kafka_server.jaas
      owner: root
      group: root
      mode: '0644'

#-------------------------------------------------------------------------------
# Disable swap for Kafka
# - Check whether swap is on: swapon -s
# - Get the swap UUID using blkid
# - Update fstab to disable swap
#-------------------------------------------------------------------------------

#   - name: install libblkid-dev
#     apt:
#       name: libblkid-dev
#       state: present
# 
#   - name: x
#     shell: blkid -s UUID -o value {{ ebs_swap }}
#     register: blkid_out
# 
#   - name: y
#     lineinfile:
#       path: /etc/fstab
#       regexp: "^UUID={{ blkid_out.stdout }}"
#       line: "UUID={{ blkid_ut.stdout }} swap  swap  defaults 0 0"

  - name: Add broker ID to each host
    template:
      src: server.properties.j2
      dest:  /etc/kafka/server.properties
